In [1]:
# Importing libraries

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [2]:
# Importing dataset
pd.options.display.max_rows

df = pd.read_csv("creditcarddefault.csv")
df.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1      20000    2          2         1   24      2      2     -1     -1   
1   2     120000    2          2         2   26     -1      2      0      0   
2   3      90000    2          2         2   34      0      0      0      0   
3   4      50000    2          2         1   37      0      0      0      0   
4   5      50000    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...          0          0          0         0       689         0   
1  ...       3272       3455       3261         0      1000      1000   
2  ...      14331      14948      15549      1518      1500      1000   
3  ...      28314      28959      29547      2000      2019      1200   
4  ...      20940      19146      19131      2000     36681     10000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0         0         0         0                           1  
1      1000         0      2000                           1  
2      1000      1000      5000                           0  
3      1100      1069      1000                           0  
4      9000       689       679                           0  

[5 rows x 25 columns]

In [3]:
# Seperating the X and y
X = df.iloc[:, :-1].values
y = df.iloc[0:, -1].values

In [4]:
# Spliting train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .20, random_state = 0)

In [32]:
# Standardizing the X_train Fit to data, then transform it.
# X_test Perform standardization by centering and scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Apply ANN

In [33]:
classifier = Sequential()
classifier.add(Dense(units =13, kernel_initializer = "uniform", activation = "relu", input_dim =24))
classifier.add(Dense(units = 13, kernel_initializer ="uniform", activation = "relu"))
classifier.add(Dense(units =1, kernel_initializer = "uniform", activation ="sigmoid"))

In [34]:
classifier.compile(optimizer="adam", loss = "binary_crossentropy", metrics = ["accuracy"])

In [35]:
classifier.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 13)                325       
_________________________________________________________________
dense_13 (Dense)             (None, 13)                182       
_________________________________________________________________
dense_14 (Dense)             (None, 1)                 14        
Total params: 521
Trainable params: 521
Non-trainable params: 0
_________________________________________________________________


In [36]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
2400/2400 [==============================] - 1s 412us/step - loss: 0.5098 - accuracy: 0.7984
Epoch 2/100
2400/2400 [==============================] - 1s 410us/step - loss: 0.4517 - accuracy: 0.8127
Epoch 3/100
2400/2400 [==============================] - 1s 409us/step - loss: 0.4477 - accuracy: 0.8155
Epoch 4/100
2400/2400 [==============================] - 1s 415us/step - loss: 0.4423 - accuracy: 0.8175
Epoch 5/100
2400/2400 [==============================] - 1s 412us/step - loss: 0.4401 - accuracy: 0.8178
Epoch 6/100
2400/2400 [==============================] - 1s 412us/step - loss: 0.4418 - accuracy: 0.8164
Epoch 7/100
2400/2400 [==============================] - 1s 413us/step - loss: 0.4356 - accuracy: 0.8179
Epoch 8/100
2400/2400 [==============================] - 1s 446us/step - loss: 0.4303 - accuracy: 0.8216
Epoch 9/100
2400/2400 [==============================] - 1s 416us/step - loss: 0.4334 - accuracy: 0.8186
Epoch 10/100
2400/2400 [==============================]

2400/2400 [==============================] - 1s 515us/step - loss: 0.4230 - accuracy: 0.8225
Epoch 79/100
2400/2400 [==============================] - 1s 508us/step - loss: 0.4206 - accuracy: 0.8226
Epoch 80/100
2400/2400 [==============================] - 1s 513us/step - loss: 0.4173 - accuracy: 0.8260
Epoch 81/100
2400/2400 [==============================] - 1s 511us/step - loss: 0.4207 - accuracy: 0.8227
Epoch 82/100
2400/2400 [==============================] - 1s 520us/step - loss: 0.4212 - accuracy: 0.8224
Epoch 83/100
2400/2400 [==============================] - 1s 509us/step - loss: 0.4177 - accuracy: 0.8229
Epoch 84/100
2400/2400 [==============================] - 1s 511us/step - loss: 0.4214 - accuracy: 0.8233
Epoch 85/100
2400/2400 [==============================] - 1s 517us/step - loss: 0.4192 - accuracy: 0.8217
Epoch 86/100
2400/2400 [==============================] - 1s 510us/step - loss: 0.4179 - accuracy: 0.8234
Epoch 87/100
2400/2400 [==============================] - 1

In [37]:
# Predicitng the X_test
y_pred = classifier.predict(X_test)

In [38]:
X_test

array([[-0.77977623, -1.14095868, -1.22772676, ..., -0.20863815,
        -0.3163186 , -0.25987201],
       [-0.48341238, -1.14095868,  0.81451348, ..., -0.3119826 ,
        -0.25038332, -0.296449  ],
       [-0.67156708,  0.48091719,  0.81451348, ..., -0.3119826 ,
        -0.3163186 , -0.296449  ],
       ...,
       [-1.29509633, -0.67756558, -1.22772676, ..., -0.21509718,
        -0.30721953, -0.293098  ],
       [ 0.32965592, -1.14095868, -1.22772676, ..., -0.3119826 ,
        -0.18444804, -0.296449  ],
       [-0.67664299, -0.90926213, -1.22772676, ...,  0.02840818,
        -0.13077673, -0.12100443]])

In [39]:
# this returns probability so convert it Binary value - 1/0 or True / False
y_pred = (y_pred > .5)

In [40]:
y_pred

array([[ True],
       [False],
       [False],
       ...,
       [False],
       [ True],
       [False]])

In [41]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

In [42]:
cm

array([[4491,  212],
       [ 859,  438]], dtype=int64)

In [43]:
print("\n ANN accuracy score ",accuracy_score(y_test,y_pred))
print("\n\n ANN classification report \n\n",classification_report(y_test,y_pred))


 ANN accuracy score  0.8215


 ANN classification report 

               precision    recall  f1-score   support

           0       0.84      0.95      0.89      4703
           1       0.67      0.34      0.45      1297

    accuracy                           0.82      6000
   macro avg       0.76      0.65      0.67      6000
weighted avg       0.80      0.82      0.80      6000

